---
# Variables for connection to deployed webservers
waf_base_url: "http://{{ hostvars[inventory_hostname].ansible_host }}:8000"
waf_username: "admin"
waf_device_name: "Welcome to CUDALAB.EU - Blue"
waf_domain: "cudalab.eu"
waf_timezone: "Europe/Amsterdam"
waf_certificate_name: "CUDALAB-2017"
waf_certificate_location: "{{ lookup('env', 'DOWNLOADSECUREFILE2_SECUREFILEPATH') }}"
waf_certificate_password: "{{ waf_password }}"
waf_service_name: "HTTPS"
waf_service_ip_address: "172.30.104.70"
waf_service_port: "443"
waf_service_type: "https"
waf_content_rule_badstore_name: "Badstore"
waf_content_rule_badstore_comment: "Badstore"
waf_content_rule_badstore_ip_address: "172.30.104.132"
waf_content_rule_badstore_port: "9200"
waf_content_rule_badstore_hostname: "az-badstore.{{ waf_domain }}"
waf_content_rule_badstore_server_name: "{{ waf_content_rule_badstore_name }}-server"
waf_content_rule_dvwa_name: "DVWA"
waf_content_rule_dvwa_comment: "Damn Vulnerable Web Application"
waf_content_rule_dvwa_ip_address: "172.30.104.132"
waf_content_rule_dvwa_port: "9100"
waf_content_rule_dvwa_hostname: "az-dvwa.{{ waf_domain }}"
waf_content_rule_dvwa_server_name: "{{ waf_content_rule_dvwa_name }}-server"
waf_content_rule_portal_name: "Portal"
waf_content_rule_portal_comment: "CUDALAB Portal"
waf_content_rule_portal_ip_address: "172.30.104.132"
waf_content_rule_portal_port: "9000"
waf_content_rule_portal_hostname: "azure.{{ waf_domain }}"
waf_content_rule_portal_server_name: "{{ waf_content_rule_portal_name }}-server"
waf_content_rule_colors_name: "Colors"
waf_content_rule_colors_comment: "Colors demo app"
waf_content_rule_colors_ip_address_1: "172.30.104.132"
waf_content_rule_colors_port_1: "9300"
waf_content_rule_colors_server_name_1: "{{ waf_content_rule_colors_name }}-server-01"
waf_content_rule_colors_ip_address_2: "172.30.104.132"
waf_content_rule_colors_port_2: "9400"
waf_content_rule_colors_server_name_2: "{{ waf_content_rule_colors_name }}-server-02"
waf_content_rule_colors_ip_address_3: "172.30.104.132"
waf_content_rule_colors_port_3: "9500"
waf_content_rule_colors_server_name_3: "{{ waf_content_rule_colors_name }}-server-03"
waf_content_rule_colors_hostname: "az-colors.{{ waf_domain }}"
