---
- file:
    path: /data/db
    state: directory
    mode: 0755

- name: Install required libraries
  apt:
    name: "{{ item.name }}"
    state: latest
    install_recommends: no
  with_items:
    - { name: 'python-mysqldb' }

- name: DB
  docker_container:
    name: db
    image: mariadb
    state: started
    pull: true
    ports:
      - "3306:3306"
    env:
      MYSQL_ROOT_PASSWORD: "{{ db_password }}"
    volumes:
     - /data/db:/var/lib/mysql

- name: Wait 300 seconds for port 3306 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 3306
    delay: 10

# Create database demo
- name: Create a new database with name 'demo'
  mysql_db:
    name: demo
    state: present
    login_host: {{ hostvars[inventory_hostname].ansible_host }}
    login_user: root
    login_password: "{{ db_password }}"

# Create database user with name 'bob' and password '12345' with all database privileges
- mysql_user:
    name: demo
    host: '%'
    password: 12345
    priv: 'demo.*:ALL'
    state: present
    login_host: {{ hostvars[inventory_hostname].ansible_host }}
    login_user: root
    login_password: "{{ db_password }}"

# Copy database dump file to remote host and restore it to database 'my_db'
- name: Copy database dump file
  copy:
    src: colors/data/colors.sql
    dest: /tmp

- name: Restore database
  mysql_db:
    name: demo
    state: import
    target: /tmp/colors.sql
    login_host: {{ hostvars[inventory_hostname].ansible_host }}
    login_user: root
    login_password: "{{ db_password }}"
